### ISSUE TITLE
show all error messages in snackbar

### ISSUE THREAD

**Issue by plazzy99** [plazzy99/Heal-O-Chat#31]
currently errors are displayed using toast. You need to convert all toast for error message to snackbar.

**Comment by lucifer0987** [comment]
@plazzy99 we need to convert all messages which are being shown with Toast to snackbar, right?

**Comment by plazzy99** [comment]
> 
> 
> @plazzy99 we need to convert all messages which are being shown with Toast to snackbar, right?

only that shows error

**Comment by lucifer0987** [comment]
@plazzy99 Got it. Can you please assign me this issue?

**Comment by lucifer0987** [comment]
> @plazzy99 Got it. Can you please assign me this issue?

@plazzy99
