### ISSUE TITLE
Hide notification bar from splash screen

### ISSUE THREAD

**Issue by plazzy99** [plazzy99/Heal-O-Chat#32]

**Comment by lucifer0987** [comment]
@plazzy99 can you please explain this issue?

**Comment by plazzy99** [comment]
> 
> 
> @plazzy99 can you please explain this issue?

yeah sure 👍🏻 
<img src="https://github.com/plazzy99/Heal-O-Chat/blob/master/app/src/main/res/drawable/splash.png" width="250"/>

In this image you see that notification bar(where battery and time is seen) is visible but it must be hidden in case of splash

**Comment by lucifer0987** [comment]
@plazzy99 got it. can you please assign me this issue?
