### ISSUE TITLE
Add Loading Dialog

### ISSUE THREAD

**Issue by plazzy99** [plazzy99/Heal-O-Chat#34]
Add up loading dialog when refreshing takes place.

**Comment by lucifer0987** [comment]
Should it be implemented everytime data of an activity/fragment is refreshed?

**Comment by plazzy99** [comment]
> 
> 
> Should it be implemented everytime data of an activity/fragment is refreshed?

yes wherever neccessary like when api or say database is called that delay time should show dialog.

**Comment by plazzy99** [comment]
> 
> 
> > Should it be implemented everytime data of an activity/fragment is refreshed?
> 
> yes wherever neccessary like when api or say database is called that delay time should show dialog.

can't assign this to you now 
max 2 issues can be assigned to 1 participant at a time.

**Comment by lucifer0987** [comment]
@plazzy99 Can you please assign this issue to me?
