### ISSUE TITLE
Displaying Chat numbers in tablayout

### ISSUE THREAD

**Issue by riturajjain2000** [plazzy99/Heal-O-Chat#48]
Display the number of unread chats in the tab layout title

![5de91d2afd9db2407b44b71a](https://user-images.githubusercontent.com/48384309/102208616-a91b9980-3ef5-11eb-83c7-e58a032cf1c1.jpg)

Something like this

**Comment by plazzy99** [comment]
Do you want this issue assigned to you?

**Comment by riturajjain2000** [comment]
> Do you want this issue assigned to you?

yes
