### ISSUE TITLE
Add delivered/seen status in chat messages

### ISSUE THREAD

**Issue by riturajjain2000** [plazzy99/Heal-O-Chat#50]
Add the famous blue tick in WhatsApp like feature in chat messages to check if the chat is seen by the receiver or not

**Comment by lucifer0987** [comment]
@plazzy99 @riturajjain2000 Can I please work on this issue?

**Comment by plazzy99** [comment]
@riturajjain2000 you want this issue to be assigned to you or should i assign to @lucifer0987

**Comment by riturajjain2000** [comment]
assign this to me , as I am already working on the #48 , which is related to this one
