### ISSUE TITLE
UI Improvement 

### ISSUE THREAD

**Issue by plazzy99** [plazzy99/Heal-O-Chat#6]
The app is built without following material design which needs to be made to make the app look better.

**Comment by Ella2996** [comment]
how can I contribute to it

**Comment by plazzy99** [comment]
post screen UI improvement(edit text)
item card of recycler view need improvements
setting screen to be improved
the color theme of the app needs to be updated.
app font according to material design
Edit profile screen needs changes.

**Comment by plazzy99** [comment]
> how can I contribute to it

these are the things you can work.

**Comment by plazzy99** [comment]
> post screen UI improvement(edit text)
> item card of recycler view need improvements
> setting screen to be improved
> the color theme of the app needs to be updated.
> app font according to material design
> Edit profile screen needs changes.

these issues will b assigned in parts mention which one you want to work

**Comment by sahil1678kumar** [comment]
how can I contribute to improving setting screen, Color theme of the app or Edit profile Screen  @plazzy99 ?

**Comment by plazzy99** [comment]
@sahil1678kumar i will update you with the screen very soon

**Comment by shivamparihar12** [comment]
Bhaiya, I want to work on this issue.

**Comment by plazzy99** [comment]
@sahil1678kumar @shivamparihar12 you both can start working on it.

**Comment by lucifer0987** [comment]
@plazzy99 Can you please assign me this issue?

**Comment by riturajjain2000** [comment]
> post screen UI improvement(edit text)
> item card of recycler view need improvements
> setting screen to be improved
> the color theme of the app needs to be updated.
> app font according to material design
> Edit profile screen needs changes.

Should we start opening the issue part by part according to these proposed changes?

**Comment by plazzy99** [comment]
Yes anyone can open proposed issue s but make sure each issue make vital and impactful change to UI.
Pull requests with less than 10 lines changes will be considered invalid and won't give you a score.
(This is so announced to prevent spam issues ans pr)
