### ISSUE TITLE
Profile Picture not getting displayed on receiver side.

### ISSUE THREAD

**Issue by riturajjain2000** [plazzy99/Heal-O-Chat#60]
The profile picture is displayed on the sender's end, but not getting displayed on the receiver's end.

![ss](https://user-images.githubusercontent.com/48384309/103174813-272f5700-488b-11eb-8203-74c3842d8836.jpg)

As you can see I have uploaded DP on the left side, It's getting uploaded to Firestore also, but not getting displayed on the emulator  that's on the right side

**Comment by plazzy99** [comment]
Have you clicked the save button after selecting the image?

**Comment by riturajjain2000** [comment]
> Have you clicked the save button after selecting the image?

yes
