### ISSUE TITLE
Show dialog if user wants to exit app

### ISSUE THREAD

**Issue by riturajjain2000** [plazzy99/Heal-O-Chat#66]
Currently, if you mistakenly press the back button while navigating the posts, cure, or chat fragments, the app is exited, which gets a little frustrating sometimes

**Comment by plazzy99** [comment]
Instead of showing dialog show a snack bar .

**Comment by riturajjain2000** [comment]
but a dialog will be better as it has 2 buttons rather than a snackbar
<img width="594" alt="Screenshot_1609249794" src="https://user-images.githubusercontent.com/48384309/103288456-ea8a6980-4a0a-11eb-9c56-7afec6c9121e.png">
Something like this, which has a negative button also, in case the user pressed the back button mistakenly

**Comment by plazzy99** [comment]
It is sometimes frustrating when this dialog comes up.
So you should add a snackbar with max 5-sec visibility on screen and 
also update the online status of the user when he clicks yes.

**Comment by riturajjain2000** [comment]
> It is sometimes frustrating when this dialog comes up.
> So you should add a snackbar with max 5-sec visibility on screen and
> also update the online status of the user when he clicks yes.

Ok!

**Comment by riturajjain2000** [comment]
Can you plz assign me this one, as it will help to recheck in the future

**Comment by plazzy99** [comment]
> Can you plz assign me this one, as it will help to recheck in the future

I forgot to do that
