### ISSUE TITLE
Go to top button on timeline

### ISSUE THREAD

**Issue by lucifer0987** [plazzy99/Heal-O-Chat#70]
We need to add a button to go to top of the page in user's timeline.

**Comment by lucifer0987** [comment]
@plazzy99 
Can you please assign me this issue?

**Comment by plazzy99** [comment]
@lucifer0987 I can't assign too many issues to you.
After raising pr for the previous assignment you can assign this one to yourself.

**Comment by lucifer0987** [comment]
@plazzy99 can you please assign this to me?
