### ISSUE TITLE
Delete for Everyone is displaying for sender's chat 

### ISSUE THREAD

**Issue by riturajjain2000** [plazzy99/Heal-O-Chat#75]
The 'delete for everyone' is appearing for the sender's chat as well as can be used to delete their chats as well. Also, it is showing unexpected behavior, sometimes you can use it, sometimes's not.

**Comment by plazzy99** [comment]
can you eloborate?

**Comment by lucifer0987** [comment]
@riturajjain2000 In telegram, Delete for everyone works on both sender's and receiver's chats.

**Comment by riturajjain2000** [comment]
> @riturajjain2000 In telegram, Delete for everyone works on both sender's and receiver's chats.

Yeah, but I think here in this app this should not be included as someone who is going through a bad state of mind should continuously be able to see the positive messages that are sent to him/her

**Comment by plazzy99** [comment]
restrict delete for everyone for opponent message

**Comment by plazzy99** [comment]
Also mention the issues. @riturajjain2000

**Comment by riturajjain2000** [comment]
> can you eloborate?
If you 'delete for everyone' a message from the sender , sometimes its still there in his/her message , also then that particular message is not delectable by the original sender

**Comment by plazzy99** [comment]
> > can you eloborate?
> 
> If you 'delete for everyone' a message from the sender , sometimes its still there in his/her message , also then that particular message is not delectable by the original sender

@lucifer0987 any comment?

After that @riturajjain2000 you can work on this issue

**Comment by lucifer0987** [comment]
> > > can you eloborate?
> > 
> > 
> > If you 'delete for everyone' a message from the sender , sometimes its still there in his/her message , also then that particular message is not delectable by the original sender
> 
> @lucifer0987 any comment?
If we require this kind of feature, then its okay. I worked on that thinking of telegram only.

**Comment by plazzy99** [comment]
> > > > can you eloborate?
> > > 
> > > 
> > > If you 'delete for everyone' a message from the sender , sometimes its still there in his/her message , also then that particular message is not delectable by the original sender
> > 
> > @lucifer0987 any comment?
> If we require this kind of feature, then its okay. I worked on that thinking of telegram only.

No about error that is comming.

**Comment by lucifer0987** [comment]
> > > > > can you eloborate?
> > > > 
> > > > 
> > > > If you 'delete for everyone' a message from the sender , sometimes its still there in his/her message , also then that particular message is not delectable by the original sender
> > > 
> > > 
> > > @lucifer0987 any comment?
> > > If we require this kind of feature, then its okay. I worked on that thinking of telegram only.
> 
> No about error that is comming.

I have never experienced any error like this and it shouldn't happen. I tested it many times.

**Comment by plazzy99** [comment]
Ok

**Comment by riturajjain2000** [comment]
> > > can you eloborate?
> > 
> > 
> > If you 'delete for everyone' a message from the sender , sometimes its still there in his/her message , also then that particular message is not delectable by the original sender
> 
> @lucifer0987 any comment?
> 
> After that @riturajjain2000 you can work on this issue

can you assign me this ?
