### ISSUE TITLE
Chat fragment Crashing if last chat message is a Image

### ISSUE THREAD

**Issue by riturajjain2000** [plazzy99/Heal-O-Chat#99]
If the last message by the sender or receiver is an Image then that's not displayed on the list and also the list activity is crashing

**Comment by plazzy99** [comment]
No nwoc tag accepting

**Comment by riturajjain2000** [comment]
> No nwoc tag accepting

np, but as Ayush said I opened this issue before the 6th EOD, so it is valid for NWOC

**Comment by riturajjain2000** [comment]
> > No nwoc tag accepting
> 
> np, but as Ayush said I opened this issue  and made a PR before the 6th EOD, so it is valid for NWOC

**Comment by riturajjain2000** [comment]
@plazzy99 you can close this now
